server:
  port: 8000


spring:
  servlet:
    multipart:
      maxFileSize: 10MB


logging:
  path: /home/demo/logs/demo-gradle-app
  config: classpath:logback-demo-gradle-app.xml


jasypt:
  file: classpath:config.properties